# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 293f7f21add5bacf6ed13e636662c9ab122b10e743d91a0e94b6b0450543f318f977f5efaf54156f9aee9b81f9a7e5c8c0f2bfc8da3cab79aefb22ffc083ca3d

test:
  secret_key_base: 3abd0cd0ea06f7b22632605d2e18252b2edf609160d0da920c6d8fb07a955f7e74e5bcc09d82e3314527cd1c457c9f3707f7154f8f596fcd6d0f37c8997b2029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
